name: 'mdsrv'
version: 0.0.2
description: A web server built using the shelf package.
#author: rxlabz <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>1.0.0 <3.0.0'

dependencies:
  args:
  shelf:
  shelf_static:
  markdown:
  meta:
  html_unescape:
  moj :
    git: git://github.com/rxlabz/m-o-j.git
  mustache:
